DROP TABLE IF EXISTS urls;

CREATE TABLE URLS
(
    ID SERIAL PRIMARY KEY,
    URL TEXT NOT NULL UNIQUE,
    TINYURL TEXT NOT NULL UNIQUE
);

CREATE UNIQUE INDEX IF NOT EXISTS id_url ON urls(url);
CREATE UNIQUE INDEX IF NOT EXISTS id_tinyurl ON urls(tinyurl);